# @name CreateEmployee
## TEST-EXPECT-STATUS: [201]
## TEST-HAS-BODY
POST {{ApiBaseUrl}}/api/employees
Content-Type: application/json

{
  "title": "Ing.",
  "fullName": "Jana Nováková",
  "email": "jana.novakova@test.com",
  "phone": "+421 900 000 002"
}

###

# @name CreateCompany
## TEST-EXPECT-STATUS: [201]
## TEST-HAS-BODY
POST {{ApiBaseUrl}}/api/companies
Content-Type: application/json

{
  "name": "Test Company Flow",
  "code": "TCF001",
  "leaderId": {{CreateEmployee.response.body.$.id}}
}

###

# @name GetCompanyById
## TEST-EXPECT-STATUS: [200]
## TEST-HAS-BODY
GET {{ApiBaseUrl}}/api/companies/{{CreateCompany.response.body.$.id}}

###

# @name UpdateCompany
## TEST-EXPECT-STATUS: [200]
PUT {{ApiBaseUrl}}/api/companies/{{CreateCompany.response.body.$.id}}
Content-Type: application/json

{
  "id": {{CreateCompany.response.body.$.id}},
  "name": "Updated Company Flow",
  "code": "TCF001-UPD",
  "leaderId": {{CreateEmployee.response.body.$.id}}
}

###

# @name DeleteCompany
## TEST-EXPECT-STATUS: [204]
DELETE {{ApiBaseUrl}}/api/companies/{{CreateCompany.response.body.$.id}}
