# @name CreateEmployee
## TEST-EXPECT-STATUS: [201]
## TEST-HAS-BODY
POST http://localhost:5223/api/employees
Content-Type: application/json

{
  "title": "Ing.",
  "fullName": "Peter Novák",
  "email": "peter.novak@test.com",
  "phone": "+421 900 000 001"
}

###

# @name CreateCompany
## TEST-EXPECT-STATUS: [201]
## TEST-HAS-BODY
POST http://localhost:5223/api/companies
Content-Type: application/json

{
  "name": "Test Company",
  "code": "TC001",
  "leaderId": {{CreateEmployee.response.body.$.id}}
}
