# @name CreateEmployee
## TEST-EXPECT-STATUS: [201]
## TEST-HAS-BODY
POST http://localhost:5223/api/employees
Content-Type: application/json

{
  "title": "Mgr.",
  "fullName": "Monika Kováčová",
  "email": "monika.kovacova@test.com",
  "phone": "+421 900 000 017"
}

###

# @name CreateCompany
## TEST-EXPECT-STATUS: [201]
## TEST-HAS-BODY
POST http://localhost:5223/api/companies
Content-Type: application/json

{
  "name": "Test Company Update",
  "code": "TCU001",
  "leaderId": {{CreateEmployee.response.body.$.id}}
}

###

## TEST-EXPECT-STATUS: [200]
PUT http://localhost:5223/api/companies/{{CreateCompany.response.body.$.id}}
Content-Type: application/json

{
  "id": {{CreateCompany.response.body.$.id}},
  "name": "Updated Company Name",
  "code": "TCU001-UPD",
  "leaderId": {{CreateEmployee.response.body.$.id}}
}
