# @name CreateEmployee
## TEST-EXPECT-STATUS: [201]
## TEST-HAS-BODY
POST http://localhost:5223/api/employees
Content-Type: application/json

{
  "title": "Ing.",
  "fullName": "Filip Nemec",
  "email": "filip.nemec@test.com",
  "phone": "+421 900 000 018"
}

###

# @name CreateCompany
## TEST-EXPECT-STATUS: [201]
## TEST-HAS-BODY
POST http://localhost:5223/api/companies
Content-Type: application/json

{
  "name": "Test Company Delete",
  "code": "TCD001",
  "leaderId": {{CreateEmployee.response.body.$.id}}
}

###

## TEST-EXPECT-STATUS: [204]
DELETE http://localhost:5223/api/companies/{{CreateCompany.response.body.$.id}}
