# @name CreateCompany
## TEST-EXPECT-STATUS: [201]
## TEST-HAS-BODY
POST http://localhost:5223/api/companies
Content-Type: application/json

{
  "name": "Test Company Delete",
  "code": "TCD001"
}

###

## TEST-EXPECT-STATUS: [204]
DELETE http://localhost:5223/api/companies/{{CreateCompany.response.body.$.id}}
