-- Universal Database Schema
-- Compatible with: PostgreSQL, MySQL, SQL Server, SQLite
-- Note: For auto-increment columns, use the appropriate syntax for your database:
--   PostgreSQL: SERIAL or GENERATED BY DEFAULT AS IDENTITY
--   MySQL: AUTO_INCREMENT
--   SQL Server: IDENTITY(1,1)
--   SQLite: INTEGER PRIMARY KEY AUTOINCREMENT

CREATE TABLE IF NOT EXISTS __EFMigrationsHistory (
    MigrationId VARCHAR(150) NOT NULL,
    ProductVersion VARCHAR(32) NOT NULL,
    CONSTRAINT PK___EFMigrationsHistory PRIMARY KEY (MigrationId)
);

-- Create Companies table
CREATE TABLE Companies (
    Id INTEGER NOT NULL PRIMARY KEY,
    Code VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    LeaderId INTEGER NOT NULL
);

-- Create Departments table
CREATE TABLE Departments (
    Id INTEGER NOT NULL PRIMARY KEY,
    Code VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    LeaderId INTEGER NOT NULL,
    ProjectId INTEGER NOT NULL
);

-- Create Employees table
CREATE TABLE Employees (
    Id INTEGER NOT NULL PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    FullName VARCHAR(255) NOT NULL,
    Phone VARCHAR(50) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    DepartmentId INTEGER NULL,
    CONSTRAINT FK_Employees_Departments_DepartmentId FOREIGN KEY (DepartmentId) REFERENCES Departments (Id)
);

-- Create Divisions table
CREATE TABLE Divisions (
    Id INTEGER NOT NULL PRIMARY KEY,
    Code VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    LeaderId INTEGER NOT NULL,
    CompanyId INTEGER NOT NULL,
    CONSTRAINT FK_Divisions_Companies_CompanyId FOREIGN KEY (CompanyId) REFERENCES Companies (Id),
    CONSTRAINT FK_Divisions_Employees_LeaderId FOREIGN KEY (LeaderId) REFERENCES Employees (Id)
);

-- Create Projects table
CREATE TABLE Projects (
    Id INTEGER NOT NULL PRIMARY KEY,
    Code VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    LeaderId INTEGER NOT NULL,
    DivisionId INTEGER NOT NULL,
    CONSTRAINT FK_Projects_Divisions_DivisionId FOREIGN KEY (DivisionId) REFERENCES Divisions (Id),
    CONSTRAINT FK_Projects_Employees_LeaderId FOREIGN KEY (LeaderId) REFERENCES Employees (Id)
);

-- Create indexes
CREATE INDEX IX_Companies_LeaderId ON Companies (LeaderId);
CREATE UNIQUE INDEX IX_Companies_Code ON Companies (Code);

CREATE INDEX IX_Departments_LeaderId ON Departments (LeaderId);
CREATE INDEX IX_Departments_ProjectId ON Departments (ProjectId);
CREATE UNIQUE INDEX IX_Departments_Code ON Departments (Code);

CREATE INDEX IX_Divisions_CompanyId ON Divisions (CompanyId);
CREATE INDEX IX_Divisions_LeaderId ON Divisions (LeaderId);
CREATE UNIQUE INDEX IX_Divisions_Code ON Divisions (Code);

CREATE INDEX IX_Employees_DepartmentId ON Employees (DepartmentId);

CREATE INDEX IX_Projects_DivisionId ON Projects (DivisionId);
CREATE INDEX IX_Projects_LeaderId ON Projects (LeaderId);
CREATE UNIQUE INDEX IX_Projects_Code ON Projects (Code);

-- Add remaining foreign keys
ALTER TABLE Companies ADD CONSTRAINT FK_Companies_Employees_LeaderId FOREIGN KEY (LeaderId) REFERENCES Employees (Id);

ALTER TABLE Departments ADD CONSTRAINT FK_Departments_Employees_LeaderId FOREIGN KEY (LeaderId) REFERENCES Employees (Id);

ALTER TABLE Departments ADD CONSTRAINT FK_Departments_Projects_ProjectId FOREIGN KEY (ProjectId) REFERENCES Projects (Id);

-- Migration history record
INSERT INTO __EFMigrationsHistory (MigrationId, ProductVersion)
VALUES ('20251116140538_InitialMigrationWithHierarchy', '9.0.11');

