CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Companies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" text NOT NULL,
    "Name" text NOT NULL,
    "LeaderId" integer,
    CONSTRAINT "PK_Companies" PRIMARY KEY ("Id")
);

CREATE TABLE "Departments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" text NOT NULL,
    "Name" text NOT NULL,
    "LeaderId" integer,
    "ProjectId" integer NOT NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
);

CREATE TABLE "Employees" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Phone" text NOT NULL,
    "Email" text NOT NULL,
    "DepartmentId" integer,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Employees_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Divisions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" text NOT NULL,
    "Name" text NOT NULL,
    "LeaderId" integer,
    "CompanyId" integer NOT NULL,
    CONSTRAINT "PK_Divisions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Divisions_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Divisions_Employees_LeaderId" FOREIGN KEY ("LeaderId") REFERENCES "Employees" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Projects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" text NOT NULL,
    "Name" text NOT NULL,
    "LeaderId" integer,
    "DivisionId" integer NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Projects_Divisions_DivisionId" FOREIGN KEY ("DivisionId") REFERENCES "Divisions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Projects_Employees_LeaderId" FOREIGN KEY ("LeaderId") REFERENCES "Employees" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Companies_LeaderId" ON "Companies" ("LeaderId");

-- Unique codes to prevent duplicates
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Companies_Code" ON "Companies" ("Code");

CREATE INDEX "IX_Departments_LeaderId" ON "Departments" ("LeaderId");

CREATE INDEX "IX_Departments_ProjectId" ON "Departments" ("ProjectId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Departments_Code" ON "Departments" ("Code");

CREATE INDEX "IX_Divisions_CompanyId" ON "Divisions" ("CompanyId");

CREATE INDEX "IX_Divisions_LeaderId" ON "Divisions" ("LeaderId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Divisions_Code" ON "Divisions" ("Code");

CREATE INDEX "IX_Employees_DepartmentId" ON "Employees" ("DepartmentId");

CREATE INDEX "IX_Projects_DivisionId" ON "Projects" ("DivisionId");

CREATE INDEX "IX_Projects_LeaderId" ON "Projects" ("LeaderId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Projects_Code" ON "Projects" ("Code");

ALTER TABLE "Companies" ADD CONSTRAINT "FK_Companies_Employees_LeaderId" FOREIGN KEY ("LeaderId") REFERENCES "Employees" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Departments" ADD CONSTRAINT "FK_Departments_Employees_LeaderId" FOREIGN KEY ("LeaderId") REFERENCES "Employees" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Departments" ADD CONSTRAINT "FK_Departments_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251116140538_InitialMigrationWithHierarchy', '9.0.11');

COMMIT;

