using KrosAssignment.Data;
using KrosAssignment.Models;
using Microsoft.EntityFrameworkCore;

namespace KrosAssignment.Endpoints;

public static class CompanyEndpoints
{
    public static void MapCompanyEndpoints(this IEndpointRouteBuilder routes)
    {
        var group = routes.MapGroup("/api/companies").WithTags("Companies");

        // GET all companies (lightweight)
        group.MapGet("/", async (AppDbContext db) =>
            await db.Companies
                .AsNoTracking()
                .ToListAsync());

        // GET company by ID
        group.MapGet("/{id:int}", async (int id, AppDbContext db) =>
        {
            var company = await db.Companies
                .Include(c => c.Leader)
                .Include(c => c.Divisions)
                .FirstOrDefaultAsync(c => c.Id == id);

            return company is null ? Results.NotFound() : Results.Ok(company);
        });

        // POST new company
        group.MapPost("/", async (Company company, AppDbContext db) =>
        {
            // Validácie
            if (string.IsNullOrWhiteSpace(company.Code))
                return Results.BadRequest(new { error = "Kód firmy je povinný." });

            if (string.IsNullOrWhiteSpace(company.Name))
                return Results.BadRequest(new { error = "Názov firmy je povinný." });

            // Overiť či existuje leader (ak je zadaný)
            if (company.LeaderId.HasValue)
            {
                var leaderExists = await db.Employees.AnyAsync(e => e.Id == company.LeaderId.Value);
                if (!leaderExists)
                    return Results.BadRequest(new { error = "Zamestnanec s týmto ID neexistuje." });
            }

            // Ensure ID is auto-generated by the database
            company.Id = 0;
            db.Companies.Add(company);
            await db.SaveChangesAsync();
            return Results.Created($"/api/companies/{company.Id}", company);
        });

        // PUT update company
        group.MapPut("/{id:int}", async (int id, Company updated, AppDbContext db) =>
        {
            var company = await db.Companies.FindAsync(id);
            if (company is null) return Results.NotFound();

            // Validácie
            if (string.IsNullOrWhiteSpace(updated.Code))
                return Results.BadRequest(new { error = "Kód firmy je povinný." });

            if (string.IsNullOrWhiteSpace(updated.Name))
                return Results.BadRequest(new { error = "Názov firmy je povinný." });

            // Overiť či existuje leader (ak je zadaný)
            if (updated.LeaderId.HasValue)
            {
                var leaderExists = await db.Employees.AnyAsync(e => e.Id == updated.LeaderId.Value);
                if (!leaderExists)
                    return Results.BadRequest(new { error = "Zamestnanec s týmto ID neexistuje." });
            }

            company.Name = updated.Name;
            company.Code = updated.Code;
            company.LeaderId = updated.LeaderId;

            await db.SaveChangesAsync();
            return Results.Ok(company);
        });

        // DELETE company
        group.MapDelete("/{id:int}", async (int id, AppDbContext db) =>
        {
            var company = await db.Companies
                .Include(c => c.Divisions)
                .FirstOrDefaultAsync(c => c.Id == id);

            if (company is null) return Results.NotFound();

            // Kontrola či firma má divízie
            if (company.Divisions.Any())
                return Results.BadRequest(new { error = "Nemožno vymazať firmu, ktorá má divízie." });

            db.Companies.Remove(company);
            await db.SaveChangesAsync();
            return Results.NoContent();
        });
    }
}
