using KrosAssignment.Data;
using KrosAssignment.Models;
using Microsoft.EntityFrameworkCore;

namespace KrosAssignment.Endpoints;

public static class DepartmentEndpoints
{
    public static void MapDepartmentEndpoints(this IEndpointRouteBuilder routes)
    {
        var group = routes.MapGroup("/api/departments").WithTags("Departments");

        // GET all departments (lightweight)
        group.MapGet("/", async (AppDbContext db) =>
            await db.Departments
                .AsNoTracking()
                .ToListAsync());

        // GET department by ID
        group.MapGet("/{id:int}", async (int id, AppDbContext db) =>
        {
            var department = await db.Departments
                .Include(d => d.Project)
                .Include(d => d.Leader)
                .Include(d => d.Employees)
                .FirstOrDefaultAsync(d => d.Id == id);

            return department is null ? Results.NotFound() : Results.Ok(department);
        });

        // GET departments by project
        group.MapGet("/by-project/{projectId:int}", async (int projectId, AppDbContext db) =>
        {
            var departments = await db.Departments
                .Where(d => d.ProjectId == projectId)
                .Include(d => d.Leader)
                .Include(d => d.Employees)
                .ToListAsync();

            return Results.Ok(departments);
        });

        // POST new department
        group.MapPost("/", async (Department department, AppDbContext db) =>
        {
            // Validácie
            if (string.IsNullOrWhiteSpace(department.Code))
                return Results.BadRequest(new { error = "Kód oddelenia je povinný." });

            if (string.IsNullOrWhiteSpace(department.Name))
                return Results.BadRequest(new { error = "Názov oddelenia je povinný." });

            // Overiť či existuje project
            var projectExists = await db.Projects.AnyAsync(p => p.Id == department.ProjectId);
            if (!projectExists)
                return Results.BadRequest(new { error = "Projekt s týmto ID neexistuje." });

            // Overiť či existuje leader (ak je zadaný)
            if (department.LeaderId.HasValue)
            {
                var leaderExists = await db.Employees.AnyAsync(e => e.Id == department.LeaderId.Value);
                if (!leaderExists)
                    return Results.BadRequest(new { error = "Zamestnanec s týmto ID neexistuje." });
            }

            // Ensure ID is auto-generated by the database
            department.Id = 0;
            db.Departments.Add(department);
            await db.SaveChangesAsync();
            return Results.Created($"/api/departments/{department.Id}", department);
        });

        // PUT update department
        group.MapPut("/{id:int}", async (int id, Department updated, AppDbContext db) =>
        {
            var department = await db.Departments.FindAsync(id);
            if (department is null) return Results.NotFound();

            // Validácie
            if (string.IsNullOrWhiteSpace(updated.Code))
                return Results.BadRequest(new { error = "Kód oddelenia je povinný." });

            if (string.IsNullOrWhiteSpace(updated.Name))
                return Results.BadRequest(new { error = "Názov oddelenia je povinný." });

            // Overiť či existuje project
            var projectExists = await db.Projects.AnyAsync(p => p.Id == updated.ProjectId);
            if (!projectExists)
                return Results.BadRequest(new { error = "Projekt s týmto ID neexistuje." });

            // Overiť či existuje leader (ak je zadaný)
            if (updated.LeaderId.HasValue)
            {
                var leaderExists = await db.Employees.AnyAsync(e => e.Id == updated.LeaderId.Value);
                if (!leaderExists)
                    return Results.BadRequest(new { error = "Zamestnanec s týmto ID neexistuje." });
            }

            department.Code = updated.Code;
            department.Name = updated.Name;
            department.LeaderId = updated.LeaderId;
            department.ProjectId = updated.ProjectId;

            await db.SaveChangesAsync();
            return Results.Ok(department);
        });

        // DELETE department
        group.MapDelete("/{id:int}", async (int id, AppDbContext db) =>
        {
            var department = await db.Departments
                .Include(d => d.Employees)
                .FirstOrDefaultAsync(d => d.Id == id);

            if (department is null) return Results.NotFound();

            // Kontrola či oddelenie má zamestnancov
            if (department.Employees.Any())
                return Results.BadRequest(new { error = "Nemožno vymazať oddelenie, ktoré má zamestnancov." });

            db.Departments.Remove(department);
            await db.SaveChangesAsync();
            return Results.NoContent();
        });
    }
}
