using KrosAssignment.Data;
using KrosAssignment.Models;
using Microsoft.EntityFrameworkCore;

namespace KrosAssignment.Endpoints;

public static class DivisionEndpoints
{
    public static void MapDivisionEndpoints(this IEndpointRouteBuilder routes)
    {
        var group = routes.MapGroup("/api/divisions").WithTags("Divisions");

        // GET all divisions (lightweight)
        group.MapGet("/", async (AppDbContext db) =>
            await db.Divisions
                .AsNoTracking()
                .ToListAsync());

        // GET division by ID
        group.MapGet("/{id:int}", async (int id, AppDbContext db) =>
        {
            var division = await db.Divisions
                .Include(d => d.Company)
                .Include(d => d.Leader)
                .Include(d => d.Projects)
                .FirstOrDefaultAsync(d => d.Id == id);

            return division is null ? Results.NotFound() : Results.Ok(division);
        });

        // GET divisions by company
        group.MapGet("/by-company/{companyId:int}", async (int companyId, AppDbContext db) =>
        {
            var divisions = await db.Divisions
                .Where(d => d.CompanyId == companyId)
                .Include(d => d.Leader)
                .Include(d => d.Projects)
                .ToListAsync();

            return Results.Ok(divisions);
        });

        // POST new division
        group.MapPost("/", async (Division division, AppDbContext db) =>
        {
            // Validácie
            if (string.IsNullOrWhiteSpace(division.Code))
                return Results.BadRequest(new { error = "Kód divízie je povinný." });

            if (string.IsNullOrWhiteSpace(division.Name))
                return Results.BadRequest(new { error = "Názov divízie je povinný." });

            // Overiť či existuje company
            var companyExists = await db.Companies.AnyAsync(c => c.Id == division.CompanyId);
            if (!companyExists)
                return Results.BadRequest(new { error = "Firma s týmto ID neexistuje." });

            // Overiť či existuje leader
            var leaderExists = await db.Employees.AnyAsync(e => e.Id == division.LeaderId);
            if (!leaderExists)
                return Results.BadRequest(new { error = "Zamestnanec s týmto ID neexistuje." });

            // Ensure ID is auto-generated by the database
            division.Id = 0;
            db.Divisions.Add(division);
            await db.SaveChangesAsync();
            return Results.Created($"/api/divisions/{division.Id}", division);
        });

        // PUT update division
        group.MapPut("/{id:int}", async (int id, Division updated, AppDbContext db) =>
        {
            var division = await db.Divisions.FindAsync(id);
            if (division is null) return Results.NotFound();

            // Validácie
            if (string.IsNullOrWhiteSpace(updated.Code))
                return Results.BadRequest(new { error = "Kód divízie je povinný." });

            if (string.IsNullOrWhiteSpace(updated.Name))
                return Results.BadRequest(new { error = "Názov divízie je povinný." });

            // Overiť či existuje company
            var companyExists = await db.Companies.AnyAsync(c => c.Id == updated.CompanyId);
            if (!companyExists)
                return Results.BadRequest(new { error = "Firma s týmto ID neexistuje." });

            // Overiť či existuje leader
            var leaderExists = await db.Employees.AnyAsync(e => e.Id == updated.LeaderId);
            if (!leaderExists)
                return Results.BadRequest(new { error = "Zamestnanec s týmto ID neexistuje." });

            division.Code = updated.Code;
            division.Name = updated.Name;
            division.LeaderId = updated.LeaderId;
            division.CompanyId = updated.CompanyId;

            await db.SaveChangesAsync();
            return Results.Ok(division);
        });

        // DELETE division
        group.MapDelete("/{id:int}", async (int id, AppDbContext db) =>
        {
            var division = await db.Divisions
                .Include(d => d.Projects)
                .FirstOrDefaultAsync(d => d.Id == id);

            if (division is null) return Results.NotFound();

            // Kontrola či divízia má projekty
            if (division.Projects.Any())
                return Results.BadRequest(new { error = "Nemožno vymazať divíziu, ktorá má projekty." });

            db.Divisions.Remove(division);
            await db.SaveChangesAsync();
            return Results.NoContent();
        });
    }
}
