using KrosAssignment.Data;
using KrosAssignment.Models;
using Microsoft.EntityFrameworkCore;

namespace KrosAssignment.Endpoints;

public static class EmployeeEndpoints
{
    public static void MapEmployeeEndpoints(this IEndpointRouteBuilder routes)
    {
        var group = routes.MapGroup("/api/employees").WithTags("Employees");

        // GET all employees (lightweight)
        group.MapGet("/", async (AppDbContext db) =>
            await db.Employees
                .AsNoTracking()
                .ToListAsync());

        // GET employee by ID
        group.MapGet("/{id:int}", async (int id, AppDbContext db) =>
        {
            var employee = await db.Employees
                .Include(e => e.Department)
                .FirstOrDefaultAsync(e => e.Id == id);

            return employee is null ? Results.NotFound() : Results.Ok(employee);
        });

        // GET employees by department
        group.MapGet("/by-department/{departmentId:int}", async (int departmentId, AppDbContext db) =>
        {
            var employees = await db.Employees
                .Where(e => e.DepartmentId == departmentId)
                .ToListAsync();

            return Results.Ok(employees);
        });

        // POST new employee
        group.MapPost("/", async (Employee employee, AppDbContext db) =>
        {
            // Validácie
            if (string.IsNullOrWhiteSpace(employee.Title))
                return Results.BadRequest(new { error = "Titul zamestnanca je povinný." });

            if (string.IsNullOrWhiteSpace(employee.FullName))
                return Results.BadRequest(new { error = "Celé meno zamestnanca je povinné." });

            if (string.IsNullOrWhiteSpace(employee.Phone))
                return Results.BadRequest(new { error = "Telefónne číslo zamestnanca je povinné." });

            if (string.IsNullOrWhiteSpace(employee.Email))
                return Results.BadRequest(new { error = "Email zamestnanca je povinný." });

            // Jednoduchá validácia formátu emailu
            if (!System.Text.RegularExpressions.Regex.IsMatch(employee.Email, @"^[^\s@]+@[^\s@]+\.[^\s@]+$"))
                return Results.BadRequest(new { error = "Neplatný formát emailu." });

            // Overiť či existuje department (ak je zadaný)
            if (employee.DepartmentId.HasValue)
            {
                var departmentExists = await db.Departments.AnyAsync(d => d.Id == employee.DepartmentId.Value);
                if (!departmentExists)
                    return Results.BadRequest(new { error = "Oddelenie s týmto ID neexistuje." });
            }

            // Ensure ID is auto-generated by the database
            employee.Id = 0;
            db.Employees.Add(employee);
            await db.SaveChangesAsync();
            return Results.Created($"/api/employees/{employee.Id}", employee);
        });

        // PUT update employee
        group.MapPut("/{id:int}", async (int id, Employee updated, AppDbContext db) =>
        {
            var employee = await db.Employees.FindAsync(id);
            if (employee is null) return Results.NotFound();

            // Validácie
            if (string.IsNullOrWhiteSpace(updated.Title))
                return Results.BadRequest(new { error = "Titul zamestnanca je povinný." });

            if (string.IsNullOrWhiteSpace(updated.FullName))
                return Results.BadRequest(new { error = "Celé meno zamestnanca je povinné." });

            if (string.IsNullOrWhiteSpace(updated.Phone))
                return Results.BadRequest(new { error = "Telefónne číslo zamestnanca je povinné." });

            if (string.IsNullOrWhiteSpace(updated.Email))
                return Results.BadRequest(new { error = "Email zamestnanca je povinný." });

            // Jednoduchá validácia formátu emailu
            if (!System.Text.RegularExpressions.Regex.IsMatch(updated.Email, @"^[^\s@]+@[^\s@]+\.[^\s@]+$"))
                return Results.BadRequest(new { error = "Neplatný formát emailu." });

            // Overiť či existuje department (ak je zadaný)
            if (updated.DepartmentId.HasValue)
            {
                var departmentExists = await db.Departments.AnyAsync(d => d.Id == updated.DepartmentId.Value);
                if (!departmentExists)
                    return Results.BadRequest(new { error = "Oddelenie s týmto ID neexistuje." });
            }

            employee.Title = updated.Title;
            employee.FullName = updated.FullName;
            employee.Phone = updated.Phone;
            employee.Email = updated.Email;
            employee.DepartmentId = updated.DepartmentId;

            await db.SaveChangesAsync();
            return Results.Ok(employee);
        });

        // DELETE employee
        group.MapDelete("/{id:int}", async (int id, AppDbContext db) =>
        {
            var employee = await db.Employees.FindAsync(id);
            if (employee is null) return Results.NotFound();

            // Kontrola či nie je zamestnanec vedúcim nejakého uzla
            var isCompanyLeader = await db.Companies.AnyAsync(c => c.LeaderId == id);
            var isDivisionLeader = await db.Divisions.AnyAsync(d => d.LeaderId == id);
            var isProjectLeader = await db.Projects.AnyAsync(p => p.LeaderId == id);
            var isDepartmentLeader = await db.Departments.AnyAsync(d => d.LeaderId == id);

            if (isCompanyLeader || isDivisionLeader || isProjectLeader || isDepartmentLeader)
                return Results.BadRequest(new { error = "Nemožno vymazať zamestnanca, ktorý je vedúcim nejakého uzla organizačnej štruktúry." });

            db.Employees.Remove(employee);
            await db.SaveChangesAsync();
            return Results.NoContent();
        });
    }
}
