using KrosAssignment.Data;
using KrosAssignment.Models;
using Microsoft.EntityFrameworkCore;

namespace KrosAssignment.Endpoints;

public static class ProjectEndpoints
{
    public static void MapProjectEndpoints(this IEndpointRouteBuilder routes)
    {
        var group = routes.MapGroup("/api/projects").WithTags("Projects");

        // GET all projects (lightweight)
        group.MapGet("/", async (AppDbContext db) =>
            await db.Projects
                .AsNoTracking()
                .ToListAsync());

        // GET project by ID
        group.MapGet("/{id:int}", async (int id, AppDbContext db) =>
        {
            var project = await db.Projects
                .Include(p => p.Division)
                .Include(p => p.Leader)
                .Include(p => p.Departments)
                .FirstOrDefaultAsync(p => p.Id == id);

            return project is null ? Results.NotFound() : Results.Ok(project);
        });

        // GET projects by division
        group.MapGet("/by-division/{divisionId:int}", async (int divisionId, AppDbContext db) =>
        {
            var projects = await db.Projects
                .Where(p => p.DivisionId == divisionId)
                .Include(p => p.Leader)
                .Include(p => p.Departments)
                .ToListAsync();

            return Results.Ok(projects);
        });

        // POST new project
        group.MapPost("/", async (Project project, AppDbContext db) =>
        {
            // Validácie
            if (string.IsNullOrWhiteSpace(project.Code))
                return Results.BadRequest(new { error = "Kód projektu je povinný." });

            if (string.IsNullOrWhiteSpace(project.Name))
                return Results.BadRequest(new { error = "Názov projektu je povinný." });

            // Overiť či existuje division
            var divisionExists = await db.Divisions.AnyAsync(d => d.Id == project.DivisionId);
            if (!divisionExists)
                return Results.BadRequest(new { error = "Divízia s týmto ID neexistuje." });

            // Overiť či existuje leader
            var leaderExists = await db.Employees.AnyAsync(e => e.Id == project.LeaderId);
            if (!leaderExists)
                return Results.BadRequest(new { error = "Zamestnanec s týmto ID neexistuje." });

            // Ensure ID is auto-generated by the database
            project.Id = 0;
            db.Projects.Add(project);
            await db.SaveChangesAsync();
            return Results.Created($"/api/projects/{project.Id}", project);
        });

        // PUT update project
        group.MapPut("/{id:int}", async (int id, Project updated, AppDbContext db) =>
        {
            var project = await db.Projects.FindAsync(id);
            if (project is null) return Results.NotFound();

            // Validácie
            if (string.IsNullOrWhiteSpace(updated.Code))
                return Results.BadRequest(new { error = "Kód projektu je povinný." });

            if (string.IsNullOrWhiteSpace(updated.Name))
                return Results.BadRequest(new { error = "Názov projektu je povinný." });

            // Overiť či existuje division
            var divisionExists = await db.Divisions.AnyAsync(d => d.Id == updated.DivisionId);
            if (!divisionExists)
                return Results.BadRequest(new { error = "Divízia s týmto ID neexistuje." });

            // Overiť či existuje leader
            var leaderExists = await db.Employees.AnyAsync(e => e.Id == updated.LeaderId);
            if (!leaderExists)
                return Results.BadRequest(new { error = "Zamestnanec s týmto ID neexistuje." });

            project.Code = updated.Code;
            project.Name = updated.Name;
            project.LeaderId = updated.LeaderId;
            project.DivisionId = updated.DivisionId;

            await db.SaveChangesAsync();
            return Results.Ok(project);
        });

        // DELETE project
        group.MapDelete("/{id:int}", async (int id, AppDbContext db) =>
        {
            var project = await db.Projects
                .Include(p => p.Departments)
                .FirstOrDefaultAsync(p => p.Id == id);

            if (project is null) return Results.NotFound();

            // Kontrola či projekt má oddelenia
            if (project.Departments.Any())
                return Results.BadRequest(new { error = "Nemožno vymazať projekt, ktorý má oddelenia." });

            db.Projects.Remove(project);
            await db.SaveChangesAsync();
            return Results.NoContent();
        });
    }
}
